article/urls.py
<<<<<<< HEAD
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'firstapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^1/$', 'article.views.basic_one'),
    url(r'^2/$', 'article.views.template_two'),
    url(r'^3/$', 'article.views.template_simple'),
    url(r'^articles/all/$', 'article.views.articles'),
    url(r'^articles/get/(?P<article_id>\d+)/$', 'article.views.article'),
    url(r'^', 'article.views.articles'),
=======
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^get/(?P<article_id>[-\d]+)/$', 'article.views.article'),
    url(r'^all/$', 'article.views.articles'),
>>>>>>> upstream/master

)

firstapp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin


admin.autodiscover()

<<<<<<< HEAD
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'firstapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^basicview/', include('article.urls')),
    url(r'^', include('article.urls')),
    url(r'^', include('name_blog.urls')),
    

)


=======
urlpatterns = patterns(
    '',
    url(r'^$', 'article.views.articles'),
    url(r'^articles/', include('article.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
>>>>>>> upstream/master

name_blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'firstapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

 
    url(r'^', 'name_blog.views.f_nameblog'),

)

article/models.py
from django.db import models

<<<<<<< HEAD
# Create your models here.

class Article(models.Model):
	class Meta():
		db_table = "article"
	article_title = models.CharField(max_length = 200)
	article_text = models.TextField()
	article_date = models.DateTimeField()
	article_likes = models.IntegerField(default = 0)

class Comments(models.Model):
	class Meta():
		db_table = "comments"
	comments_text = models.TextField()
	comments_article = models.ForeignKey(Article)
=======

class Article(models.Model):
    class Meta():
        db_table = "article"
    article_title = models.CharField(max_length=200)
    article_text = models.TextField()
    article_date = models.DateTimeField()
    article_likes = models.IntegerField(default=0)


class Comments(models.Model):
    class Meta():
        db_table = "comments"
    comments_text = models.TextField()
    comments_article = models.ForeignKey(Article)
>>>>>>> upstream/master

name_blog/models.py
from django.db import models

# Create your models here.

class NameBlog(models.Model):
	class Meta():
		db_table = "nameblog"
	name_blog = models.TextField(max_length=100)
	

article/views.py
from django.shortcuts import render
<<<<<<< HEAD
from django.http.response import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
from article.models import Article, Comments

# Create your views here.

def basic_one(request):
	view = 'basic_one'
	html = "<html><body>This is %s view</html></body>" % view
	return HttpResponse(html)

def template_two(request):
	view = "template_two"
	t = get_template('myview.html')
	html = t.render(Context({'name': view}))
	return HttpResponse(html)

def template_simple(request):
	view = "template_three"
	return render_to_response('myview.html', {'name': view})

def articles(request):
	return render_to_response('articles.html', {'articles': Article.objects.all()})

def article(request, article_id=1):
	return render_to_response('article.html', {'article': Article.objects.get(id=article_id), 'comments': Comments.objects.filter(comments_article_id=article_id)})

=======
from article.models import Article, Comments


def articles(request):
    return render(request, 'articles.html', {
        'articles': Article.objects.all(),
    })


def article(request, article_id=1):
    print dir(Article.objects.get(id=article_id))
    return render(request, 'article.html', {
        'article': Article.objects.get(id=article_id),
        'comments': Comments.objects.filter(comments_article_id=article_id),
    })
>>>>>>> upstream/master

name_blog/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from name_blog.models import NameBlog

# Create your views here.

def f_nameblog(request):
	return render_to_response('nameblog.html', {'name': NameBlog.objects.all()})

article/templates/article.html
<<<<<<< HEAD
{% extends 'main.html' %}

{% block article %}
<h4>{{ article.article_date }}</h4>
<h2>{{ article.article_title }}</h2>
<p>{{ article.article_text }}</p>
<hr>
<p>Комментарии</p>
{% for comment in comments %}
	<p>{{ comment.comments_text }}</p>
{% endfor %}
{% endblock %}
=======
{% extends 'base.html' %}

{% block content %}

<h4>{{ article.article_date }}</h4>
<h2>{{ article.article_title }}</h2>
<p>{{ article.article_text }}</p>

<hr>

<p>Комментарии</p>

{% for comment in article.comments_set.all %}

	<p>{{ comment.comments_text }}</p>

{% endfor %}

{% endblock content %}
>>>>>>> upstream/master

article/templates/articles.html
<<<<<<< HEAD
{% extends 'main.html' %}

{% block article %}
{% for article in articles %}
=======
{% extends 'base.html' %}

{% block content %}

{% for article in articles %}

>>>>>>> upstream/master
	<h6>Дата публикации: {{ article.article_date }}</h6>
	<h4><a href="/articles/get/{{ article.id }}">{{ article.article_title }}</a></h4>
	<p>{{ article.article_text }}</p>
	<p>Понравилось: {{ article.article_likes }}</p>
<<<<<<< HEAD
	<hr>
{% endfor %}
{% endblock %}
=======

	<hr>

{% endfor %}

{% endblock content %}
>>>>>>> upstream/master

name_blog/templates/nameblog.html
{% extends 'main.html' %}

{% block nameblog %}
<h1> {{ name.name_blog }} </h1>
{% endblock %}

templates/main.html
 <!DOCTYPE html>
<html>
<head>
	<title> Django blog </title>
</head>
<body>
{% block nameblog %}{% endblock %}
{% block article %}{% endblock %}

</body>
</html>

templates/myview.html
<!DOCTYPE html>
<html>
<body>
This is {{ name }} view
</body>
</html>